apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  strategy:
    blueGreen:
      activeService: kargo-demo
      autoPromotionEnabled: true
    steps:
    - setWeight: 20
    - pause: {}
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.29.2
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
      volumes:
      - configMap:
          name: kargo-demo-content
        name: content
